travis:
  secure:
    BINSTAR_TOKEN: BFUxUHd+6je8Ix7dwuIAH613DnhINTUouxANT3Z1ILSbgP+OZlymcl4mptecb4y9haSCoBQ/GZcpSpTM25bSLuAA9w3W0j48b2/lrjcygmIOqJ3iZ5Wg0zT2xcxeGQ2FhR6gtU1wfKoGRDrxmeCP6gfLHSp6eP7zdeeiyoTm+2I3TWG65m+wIDgZgkh4gVxs+3z1eds/BgL04OEktKHoUwbAkdug8fyaHoo77u5LTErX9vSBvj+iQatiC3pZoGdEPCcfD7qQRTv3cT8zGxzGnx3/pF8CvSVc7bIlpX8merkrcH5KYHLEi1rx3U2kbFWFdWRLFVuc/9Q3N9u5rBB8rXkYj0dyfaKnoInHSqG8dVCi/aj51qEvSWz+LFcgS4XI9v/715KAo2CSPNDLHwfluwwil0Rb5j20uPwYKx5jznqbAx7zRHgr7n8xgX8odvRxIVz12RoUO3wQtxorJWXbpHYsidXIBLuv2sjX5H0O3a9E7QMoR042c8D0Ha3GEzxFqvAAjkUPWe5/R7sy5YoMlsWr8d+kFzieBq263aLwaF9QCg5Aa8i0DQjRm0AYVEa64HcomkxptBP2ml+DlTNHuk52lXmmVPh/h3rjyW7JJ4dXPoPvwcAoodEthBuyd1dRmmPFyca67tPNo7QejOa3AfZ/wMYG/wuTbepRPedfkZI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
