appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mpUL5FgWPxnyb3k0HBc2eyyPIlLibr6sodIZ05IEefSZH2U6hpXGyq833TtOTMYrStwSQuTyA5BG5rjuz9g979XFbtLxRAQ6ngP9rU4gD4JjzKlvzo32hy2mQA/l4r8/BRM4IrzXq96FLDWRD2nFmnSKijGTsU/V7PWE0rEGfttykHyyijSFFb1MEMR3M+cCZyxsudOVb7UoWkPO6v8xYB4ly1qOQOkWuZtEQVMAepLEigrDH+LFKbtd9f+9f8btH5T4wMWoxAcg28zwNLG+p6c9W41U1XPeuW2ASMxZQHQ2/F47/WDDY8u2/QIdZUKFu3vfh6AWHqWY7/yIPr+19gzkbi6ECyMcCgPVlUEeY3NzraVSRa+jxUEkGcjgxDVA8OvM6ZYb+Yn5yPeGmPV0GICL2DX50a/L9d7bhUEfdcog/sBuMxAvJQE6Qdh6MyS6aPxhcPru9ma99BiFtATD9d40G0q0TsGP9kqHkszqriTqpIZ0FcY66PpIeCAyqasWKChxTjFbWFH/FhCbXApjpFHQb2dodS+eG9wCy0ROKG7izu38GjlGPxNz4cLDbiWY2dAC1lrA+FQIAkTd1V1EoTgAACZOSQGwnETtICUFPEJlKUYzyclQJndSptq31+7qr0i3nthCyqTbxJPof+WwNzM61vyL8Xx9GFjvGW6G6gE=}
